{% extends 'partial/layout.swig' %}
{% block title -%}Woo的博客{%- endblock %}
{% block content -%}
<div>
	<p>
		真丝woo的博客？
	</p>
</div>
{%- endblock %}
{% block table_1 -%}
<div>
	<table class="tblcss">
	<tr>
		<td>test1</td>
		<td>test2</td>
		<td>test1</td>
	</tr>
	<tr>
		<td>test1</td>
		<td>test2</td>
		<td>test1</td>
	</tr>
	<tr>
		<td>test1</td>
		<td>test2</td>
		<td>test1</td>
	</tr>
	</table>
</div>
{%- endblock %}
